[colors]
background = #282a36
background-alt = #44475a
foreground = #f8f8f2
primary = #bd93f9
secondary = #8be9fd
alert = #ff5555
disabled = #6272a4
green = #50fa7b
yellow = #f1fa8c

[bar/bar1]
width = 100%
height = 24pt
; Corner radius ain kala
radius = 0

fixed-center = true
bottom = false

background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt

padding-left = 1
padding-right = 1
module-margin = 1
separator = " "
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Nerd Font:size=10;3"
font-1 = "JetBrainsMono Nerd Font:size=12;3"

; Modules arrangement
modules-left = i3 xwindow
modules-center = custom-text
modules-right = systray wlan eth pulseaudio memory cpu date

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

wm-restack = i3
override-redirect = true

[module/systray]
type = internal/tray
format-margin = 0pt
tray-spacing = 8pt
tray-size = 65%

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-padding = 2

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:20:...%
label-foreground = ${colors.secondary}
label-padding = 1

[module/custom-text]
type = custom/text
; Mabox Logo saha word eka center ekata
content = "   Mabox Linux "
content-foreground = ${colors.primary}
content-font = 2

[module/wlan]
type = internal/network
interface-type = wireless
interval = 3.0
click-left = nm-connection-editor &
format-connected = <label-connected>
label-connected = %essid%
label-connected-foreground = ${colors.foreground}
label-connected-padding = 1
format-disconnected = ""

[module/eth]
type = internal/network
interface-type = wired
interval = 3.0
click-left = nm-connection-editor &
format-connected = <label-connected>
label-connected = Ethernet
label-connected-foreground = ${colors.foreground}
label-connected-padding = 1
format-disconnected = ""

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.secondary}
label-volume = %percentage%%
label-muted = "󰝟 "
label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰻠 "
format-prefix-foreground = ${colors.yellow}
label = %percentage:2%%

[module/date]
type = internal/date
interval = 1
date = %I:%M %p
label = %date%
label-foreground = ${colors.primary}
format-prefix = "󰃭 "
format-prefix-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true
